# Generated by Django 4.2.3 on 2023-07-23 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата изготовления'),
        ),
    ]
